global:
  resolve_timeout: 5m
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: telegram
  routes:
  # Only important alerts.
   - match_re:
       severity: ^(oncall|critical)$
     receiver: telegram-oncall

receivers:
- name: telegram
  webhook_configs:
  - url: 'http://alertgram:8080/alerts'
    send_resolved: true

- name: telegram-oncall
  webhook_configs:
  - url: 'http://alertgram:8080/alerts?chat-id=-4592173189'


